events {}

http {
    server {
        listen 80;

        # FRONTEND
        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # AUTH SERVICE
        location /auth/ {
            proxy_pass http://auth-service:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # PROFILE SERVICE
        location /users/ {
            proxy_pass http://profiles-service:8083/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # COMPANY SERVICE
        location /companies/ {
            proxy_pass http://company-service:8082/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # OPTIONAL DIRECT ROUTES
        location /me {
            proxy_pass http://auth-service:8080/me;
        }

        location /verify {
            proxy_pass http://auth-service:8080/verify;
        }

        location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    }
}