package com.handshaker.profiles_service.enums;

public enum JobProfession {

    // TRANSPORTATION
    TRUCK_DRIVER_C(JobCategory.TRANSPORTATION),
    TAXI_DRIVER(JobCategory.TRANSPORTATION),
    VAN_DRIVER_B(JobCategory.TRANSPORTATION),
    BUS_DRIVER_D(JobCategory.TRANSPORTATION),
    FORKLIFT_OPERATOR(JobCategory.TRANSPORTATION),
    WAREHOUSE_WORKER(JobCategory.TRANSPORTATION),
    DELIVERY_PERSON(JobCategory.TRANSPORTATION),
    LOADING_OPERATOR(JobCategory.TRANSPORTATION),
    TRANSPORTATION_OTHER(JobCategory.TRANSPORTATION),

    // CONSTRUCTION
    MASON(JobCategory.CONSTRUCTION),
    CARPENTER_FORMWORK(JobCategory.CONSTRUCTION),
    REBAR_WORKER(JobCategory.CONSTRUCTION),
    FACADE_WORKER(JobCategory.CONSTRUCTION),
    TILE_LAYER(JobCategory.CONSTRUCTION),
    PAINTER(JobCategory.CONSTRUCTION),
    PLUMBER(JobCategory.CONSTRUCTION),
    ELECTRICIAN(JobCategory.CONSTRUCTION),
    ROOFER(JobCategory.CONSTRUCTION),
    CONCRETE_WORKER(JobCategory.CONSTRUCTION),
    JOINER(JobCategory.CONSTRUCTION),
    METALWORKER(JobCategory.CONSTRUCTION),
    DRYWALL_WORKER(JobCategory.CONSTRUCTION),
    CHIMNEY_SWEEP(JobCategory.CONSTRUCTION),
    CONSTRUCTION_OTHER(JobCategory.CONSTRUCTION),

    // HOSPITALITY
    COOK(JobCategory.HOSPITALITY),
    KITCHEN_HELPER(JobCategory.HOSPITALITY),
    WAITER(JobCategory.HOSPITALITY),
    BARTENDER(JobCategory.HOSPITALITY),
    RECEPTIONIST(JobCategory.HOSPITALITY),
    HOUSEKEEPER(JobCategory.HOSPITALITY),
    PIZZA_MAKER(JobCategory.HOSPITALITY),
    PASTRY_CHEF(JobCategory.HOSPITALITY),
    BAKER(JobCategory.HOSPITALITY),
    BARISTA(JobCategory.HOSPITALITY),
    HOSPITALITY_OTHER(JobCategory.HOSPITALITY),

    // MANUFACTURING
    WELDER(JobCategory.MANUFACTURING),
    ASSEMBLY_WORKER(JobCategory.MANUFACTURING),
    CNC_OPERATOR(JobCategory.MANUFACTURING),
    MECHANICAL_TECHNICIAN(JobCategory.MANUFACTURING),
    QUALITY_CONTROLLER(JobCategory.MANUFACTURING),
    PRODUCTION_LINE_WORKER(JobCategory.MANUFACTURING),
    ELECTROMECHANICIAN(JobCategory.MANUFACTURING),
    MANUFACTURING_OTHER(JobCategory.MANUFACTURING),

    // CLEANING
    CLEANER(JobCategory.CLEANING),
    WINDOW_CLEANER(JobCategory.CLEANING),
    INDUSTRIAL_CLEANER(JobCategory.CLEANING),
    MUNICIPAL_WORKER(JobCategory.CLEANING),
    GARDENER(JobCategory.CLEANING),
    HANDYMAN(JobCategory.CLEANING),
    CLEANING_OTHER(JobCategory.CLEANING),

    // AGRICULTURE
    PICKER(JobCategory.AGRICULTURE),
    GREENHOUSE_WORKER(JobCategory.AGRICULTURE),
    FARM_WORKER(JobCategory.AGRICULTURE),
    TRACTOR_OPERATOR(JobCategory.AGRICULTURE),
    VINEYARD_WORKER(JobCategory.AGRICULTURE),
    LIVESTOCK_WORKER(JobCategory.AGRICULTURE),
    AGRICULTURE_OTHER(JobCategory.AGRICULTURE);


    private final JobCategory category;

    JobProfession(JobCategory category) {
        this.category = category;
    }

    public JobCategory getCategory() {
        return category;
    }
}
